on: 
  push:
  schedule:
    - cron: "30 13 99 * *"
  workflow_dispatch:

jobs:
  test-p:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Setup Python environment
        uses: actions/setup-python@v2
        with:
            python-version: '3.8'
            architecture: 'x64'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: bbi.py
        run: |
          python bbi.py
      - name: Update resources
        uses: test-room-7/action-update-file@v1
        with:
            file-path: |
              CHG.json
            github-token: ${{ secrets.GITHUB_TOKEN }}
            commit-msg: Fetched Data | Update per Month
            branch: data
