on: 
  push:
  schedule:
    - cron: "30 15 7,14,21,28 * *"
  workflow_dispatch:

jobs:
  test-p:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Setup Python environment
        uses: actions/setup-python@v2
        with:
            python-version: '3.8'
            architecture: 'x64'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: main2.py
        run: |
          python main2.py
      - name: Update resources
        uses: test-room-7/action-update-file@v1
        with:
            file-path: |
              _rtlist.json
              _stoplist.json
              _nearlist.json
            github-token: ${{ secrets.GITHUB_TOKEN }}
            commit-msg: Fetched Data | Update per week
            branch: data
